# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Seguradora',
                'verbose_name_plural': 'Seguradoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Apolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apolice', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('FROTA', 'Seguro de Frota'), ('CARGA', 'Seguro de Carga'), ('RCFDC', 'RCFDC'), ('RCF', 'RCF'), ('VIDA', 'Seguro de Vida'), ('OUTRO', 'Outro')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_cobertura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('franquia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('RENOVADA', 'Renovada')], default='ATIVA', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apolices', to='transportador_empresas.empresa')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apolices', to='frota.vehicle')),
                ('seguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apolices', to='seguros.seguradora')),
            ],
            options={
                'verbose_name': 'Apólice',
                'verbose_name_plural': 'Apólices',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Sinistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sinistro', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('COLISAO', 'Colisão'), ('ROUBO', 'Roubo/Furto'), ('INCENDIO', 'Incêndio'), ('DANOS_CARGA', 'Danos à Carga'), ('TERCEIROS', 'Danos a Terceiros'), ('OUTRO', 'Outro')], max_length=20)),
                ('data_ocorrencia', models.DateTimeField()),
                ('data_abertura', models.DateField(default=django.utils.timezone.now)),
                ('local_ocorrencia', models.CharField(max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('descricao', models.TextField()),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_aprovado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_franquia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('NEGADO', 'Negado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('boletim_ocorrencia', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('apolice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sinistros', to='seguros.apolice')),
            ],
            options={
                'verbose_name': 'Sinistro',
                'verbose_name_plural': 'Sinistros',
                'ordering': ['-data_ocorrencia'],
            },
        ),
    ]
