# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('padrao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('layout_json', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('FROTA', 'Frota'), ('FINANCEIRO', 'Financeiro'), ('OPERACIONAL', 'Operacional'), ('MANUTENCAO', 'Manutenção'), ('ENTREGAS', 'Entregas'), ('CUSTOS', 'Custos')], max_length=20)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('meta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unidade', models.CharField(help_text='Ex: R$, %, km, un', max_length=20)),
                ('data_referencia', models.DateField(default=django.utils.timezone.now)),
                ('formula_sql', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('KPI', 'KPI'), ('GRAFICO_LINHA', 'Gráfico de Linha'), ('GRAFICO_BARRA', 'Gráfico de Barra'), ('GRAFICO_PIZZA', 'Gráfico de Pizza'), ('TABELA', 'Tabela'), ('MAPA', 'Mapa'), ('LISTA', 'Lista')], max_length=20)),
                ('fonte_dados', models.CharField(max_length=200)),
                ('posicao_x', models.IntegerField(default=0)),
                ('posicao_y', models.IntegerField(default=0)),
                ('largura', models.IntegerField(default=4)),
                ('altura', models.IntegerField(default=4)),
                ('configuracao_json', models.JSONField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.dashboard')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['dashboard', 'posicao_y', 'posicao_x'],
            },
        ),
    ]
