# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('tipo_analise', models.CharField(choices=[('imagem', 'Análise de Imagem'), ('video', 'Análise de Vídeo'), ('audio', 'Análise de Áudio')], max_length=50)),
                ('arquivo', models.FileField(upload_to='ia_analises/')),
                ('resultado', models.JSONField()),
                ('precisao', models.FloatField(default=0.0)),
                ('tempo_processamento', models.FloatField(default=0.0)),
                ('status', models.CharField(default='processando', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análise de IA',
                'verbose_name_plural': 'Análises de IA',
                'ordering': ['-data_analise'],
            },
        ),
        migrations.CreateModel(
            name='Gamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('nivel', models.CharField(choices=[('bronze', 'Bronze'), ('prata', 'Prata'), ('ouro', 'Ouro'), ('platina', 'Platina')], default='bronze', max_length=20)),
                ('conquistas', models.JSONField(default=list)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gamificação',
                'verbose_name_plural': 'Gamificações',
                'ordering': ['-pontos'],
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('negada', 'Negada')], default='aberta', max_length=20)),
                ('hash_blockchain', models.CharField(blank=True, max_length=64)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='ia_pneus.analiseia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garantia',
                'verbose_name_plural': 'Garantias',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
