# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Posto de Combustível',
                'verbose_name_plural': 'Postos de Combustível',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abastecimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_combustivel', models.CharField(choices=[('DIESEL_S10', 'Diesel S10'), ('DIESEL_S500', 'Diesel S500'), ('DIESEL_ADITIVADO', 'Diesel Aditivado'), ('ARLA32', 'Arla 32'), ('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol')], max_length=30)),
                ('litros', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco_litro', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_veiculo', models.IntegerField()),
                ('km_desde_ultimo', models.IntegerField(blank=True, null=True)),
                ('consumo_medio', models.DecimalField(blank=True, decimal_places=2, help_text='KM/L', max_digits=5, null=True)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('VALE', 'Vale Combustível'), ('FATURADO', 'Faturado')], max_length=20)),
                ('numero_nota', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('motorista_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('tanque_cheio', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='frota.vehicle')),
                ('posto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='combustivel.postocombustivel')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data_abastecimento'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('total_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_rodado', models.IntegerField()),
                ('consumo_medio', models.DecimalField(decimal_places=2, help_text='KM/L', max_digits=5)),
                ('custo_por_km', models.DecimalField(decimal_places=4, max_digits=10)),
                ('numero_abastecimentos', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_mensal', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Consumo Mensal',
                'verbose_name_plural': 'Consumos Mensais',
                'ordering': ['-mes_referencia'],
                'unique_together': {('veiculo', 'mes_referencia')},
            },
        ),
    ]
