# Generated by Django 5.2.7 on 2025-10-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustivel', '0001_initial'),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o abastecimento pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o abastecimento está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='consumomensal',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o consumo mensal pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_mensais', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='consumomensal',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o consumo mensal está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_mensais', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='postocombustivel',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o posto de combustível pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postos_combustivel', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='postocombustivel',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o posto de combustível está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postos_combustivel', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
    ]
