#!/usr/bin/env bash
# exit on error
set -o errexit

# Install Python dependencies
python3.11 -m pip install --upgrade pip
python3.11 -m pip install -r requirements.txt

export DJANGO_SETTINGS_MODULE=config.render_production
# Collect static files
python3.11 manage.py collectstatic --no-input
# Validate that the admin assets are present in the manifest generated by collectstatic
python3.11 <<'PY'
import json
import sys
from pathlib import Path

manifest_path = Path("staticfiles/staticfiles.json")

if not manifest_path.exists():
    sys.exit("collectstatic did not produce staticfiles/staticfiles.json")

data = json.loads(manifest_path.read_text())
paths = data.get("paths") or {}

if "admin/css/base.css" not in paths:
    sys.exit("Missing admin/css/base.css entry in staticfiles manifest; collectstatic may have failed")
PY

# Run migrations
python3.11 manage.py migrate

# Note: Removed automatic creation of admin and test users for security.
