FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
RUN python3.11 -m pip install --no-cache-dir pip==24.0
COPY requirements.txt /app/requirements.txt
RUN python3.11 -m pip install --no-cache-dir -r /app/requirements.txt && \
    python3.11 -m pip install dj-database-url
COPY . /app
EXPOSE 8000
