# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CercaEletronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('CIRCULAR', 'Circular'), ('POLIGONAL', 'Poligonal'), ('ROTA', 'Rota')], max_length=20)),
                ('latitude_centro', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude_centro', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('raio', models.IntegerField(blank=True, help_text='Raio em metros', null=True)),
                ('coordenadas_json', models.JSONField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('alertar_entrada', models.BooleanField(default=False)),
                ('alertar_saida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cercas', to='transportador_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cerca Eletrônica',
                'verbose_name_plural': 'Cercas Eletrônicas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('velocidade', models.IntegerField(default=0, help_text='Velocidade em km/h')),
                ('direcao', models.IntegerField(blank=True, help_text='Direção em graus (0-360)', null=True)),
                ('altitude', models.IntegerField(blank=True, help_text='Altitude em metros', null=True)),
                ('precisao', models.DecimalField(blank=True, decimal_places=2, help_text='Precisão em metros', max_digits=5, null=True)),
                ('ignicao_ligada', models.BooleanField(default=False)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Posição GPS',
                'verbose_name_plural': 'Posições GPS',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ViolacaoCerca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('RECONHECIDO', 'Reconhecido'), ('RESOLVIDO', 'Resolvido'), ('IGNORADO', 'Ignorado')], default='ABERTO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('cerca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violacoes', to='rastreamento.cercaeletronica')),
                ('posicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violacoes', to='rastreamento.posicao')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violacoes_cerca', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Violação de Cerca',
                'verbose_name_plural': 'Violações de Cercas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoRastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('km_percorrido', models.IntegerField(default=0)),
                ('tempo_movimento', models.IntegerField(default=0, help_text='Tempo em movimento (minutos)')),
                ('tempo_parado', models.IntegerField(default=0, help_text='Tempo parado (minutos)')),
                ('velocidade_maxima', models.IntegerField(default=0)),
                ('velocidade_media', models.IntegerField(default=0)),
                ('numero_paradas', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_rastreamento', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Histórico de Rastreamento',
                'verbose_name_plural': 'Históricos de Rastreamento',
                'ordering': ['-data'],
                'unique_together': {('veiculo', 'data')},
            },
        ),
        migrations.AddIndex(
            model_name='posicao',
            index=models.Index(fields=['veiculo', '-data_hora'], name='rastreament_veiculo_464867_idx'),
        ),
    ]
