# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_viagem', models.CharField(max_length=50, unique=True)),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('data_saida_prevista', models.DateTimeField()),
                ('data_chegada_prevista', models.DateTimeField()),
                ('data_saida_real', models.DateTimeField(blank=True, null=True)),
                ('data_chegada_real', models.DateTimeField(blank=True, null=True)),
                ('km_inicial', models.IntegerField()),
                ('km_final', models.IntegerField(blank=True, null=True)),
                ('km_percorrido', models.IntegerField(blank=True, null=True)),
                ('motorista_nome', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('despesas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='transportador_empresas.empresa')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-data_saida_prevista'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ABASTECIMENTO', 'Abastecimento'), ('DESCANSO', 'Descanso'), ('REFEICAO', 'Refeição'), ('MANUTENCAO', 'Manutenção'), ('CARGA', 'Carga'), ('DESCARGA', 'Descarga'), ('FISCALIZACAO', 'Fiscalização'), ('OUTRO', 'Outro')], max_length=20)),
                ('local', models.CharField(max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('data_hora_entrada', models.DateTimeField()),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('duracao_minutos', models.IntegerField(blank=True, null=True)),
                ('km_veiculo', models.IntegerField(blank=True, null=True)),
                ('valor_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='viagens.viagem')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['viagem', 'data_hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=10)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Volume em m³', max_digits=10, null=True)),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_mercadoria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente_nome', models.CharField(max_length=200)),
                ('cliente_cpf_cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='viagens.viagem')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'ordering': ['viagem', 'id'],
            },
        ),
    ]
