# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_entregaepi', to='transportador_empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'EntregaEPI',
                'verbose_name_plural': 'EntregaEPIs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_epi', to='transportador_empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FichaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_fichaepi', to='transportador_empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'FichaEPI',
                'verbose_name_plural': 'FichaEPIs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TipoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_tipoepi', to='transportador_empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'TipoEPI',
                'verbose_name_plural': 'TipoEPIs',
                'ordering': ['-criado_em'],
            },
        ),
    ]
