# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tempo_estimado_minutos', models.IntegerField(blank=True, null=True)),
                ('data_inicio_prevista', models.DateTimeField()),
                ('data_fim_prevista', models.DateTimeField()),
                ('data_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('data_fim_real', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('custo_combustivel_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_pedagio_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='transportador_empresas.empresa')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-data_inicio_prevista'],
            },
        ),
        migrations.CreateModel(
            name='RotaOtimizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoritmo', models.CharField(help_text='Algoritmo utilizado (ex: Dijkstra, A*)', max_length=50)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_estimado_minutos', models.IntegerField()),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('economia_distancia_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('economia_tempo_minutos', models.IntegerField(default=0)),
                ('economia_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sequencia_pontos_json', models.JSONField()),
                ('detalhes_json', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('rota_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otimizacoes', to='rotas.rota')),
            ],
            options={
                'verbose_name': 'Rota Otimizada',
                'verbose_name_plural': 'Rotas Otimizadas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PontoRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ORIGEM', 'Origem'), ('PARADA', 'Parada'), ('DESTINO', 'Destino'), ('PEDAGIO', 'Pedágio'), ('POSTO', 'Posto de Combustível'), ('DESCANSO', 'Ponto de Descanso')], max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('tempo_parada_minutos', models.IntegerField(default=0)),
                ('chegada_prevista', models.DateTimeField(blank=True, null=True)),
                ('chegada_real', models.DateTimeField(blank=True, null=True)),
                ('saida_prevista', models.DateTimeField(blank=True, null=True)),
                ('saida_real', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='rotas.rota')),
            ],
            options={
                'verbose_name': 'Ponto da Rota',
                'verbose_name_plural': 'Pontos da Rota',
                'ordering': ['rota', 'ordem'],
                'unique_together': {('rota', 'ordem')},
            },
        ),
    ]
