# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CRLV', 'CRLV'), ('CNH', 'CNH'), ('ANTT', 'ANTT'), ('SEGURO', 'Seguro'), ('LICENCA_AMBIENTAL', 'Licença Ambiental'), ('CERTIFICADO_TACOGRAFO', 'Certificado Tacógrafo'), ('ALVARA', 'Alvará'), ('OUTRO', 'Outro')], max_length=30)),
                ('numero', models.CharField(max_length=100)),
                ('orgao_emissor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField()),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('VENCIDO', 'Vencido'), ('VENCENDO', 'Vencendo'), ('RENOVADO', 'Renovado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['data_validade'],
            },
        ),
    ]
