# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_produto', to='transportador_empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produto',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True, verbose_name='Código')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, verbose_name='Código de Barras')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('estoque_minimo', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Estoque Mínimo')),
                ('estoque_maximo', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Estoque Máximo')),
                ('ponto_reposicao', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Ponto de Reposição')),
                ('custo_medio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Custo Médio')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Preço de Venda')),
                ('ncm', models.CharField(blank=True, max_length=8, verbose_name='NCM')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.categoriaproduto', verbose_name='Categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='transportador_empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste'), ('DEVOLUCAO', 'Devolução')], max_length=20, verbose_name='Tipo')),
                ('data_movimentacao', models.DateTimeField(verbose_name='Data da Movimentação')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total')),
                ('documento_referencia', models.CharField(blank=True, max_length=50, verbose_name='Documento de Referência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='CurvaABC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(verbose_name='Período Início')),
                ('periodo_fim', models.DateField(verbose_name='Período Fim')),
                ('valor_total_vendas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total de Vendas')),
                ('percentual_acumulado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Percentual Acumulado')),
                ('classificacao', models.CharField(choices=[('A', 'Classe A (80% do valor)'), ('B', 'Classe B (15% do valor)'), ('C', 'Classe C (5% do valor)')], max_length=1, verbose_name='Classificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curvas_abc', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Curva ABC',
                'verbose_name_plural': 'Curvas ABC',
                'ordering': ['classificacao', '-valor_total_vendas'],
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Quantidade')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total')),
                ('data_ultima_movimentacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Movimentação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Saldo de Estoque',
                'verbose_name_plural': 'Saldos de Estoque',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('qtd', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('data', models.CharField(blank=True, max_length=20, verbose_name='Data')),
                ('obs', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_antigas', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque (Legado)',
                'verbose_name_plural': 'Movimentações de Estoque (Legado)',
            },
        ),
        migrations.CreateModel(
            name='PrevisaoDemanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(verbose_name='Mês de Referência')),
                ('quantidade_prevista', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Quantidade Prevista')),
                ('quantidade_real', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Quantidade Real')),
                ('metodo_previsao', models.CharField(choices=[('MEDIA_MOVEL', 'Média Móvel'), ('MEDIA_PONDERADA', 'Média Ponderada'), ('TENDENCIA', 'Tendência'), ('SAZONALIDADE', 'Sazonalidade')], default='MEDIA_MOVEL', max_length=50, verbose_name='Método de Previsão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes_demanda', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Previsão de Demanda',
                'verbose_name_plural': 'Previsões de Demanda',
                'ordering': ['-mes_referencia'],
                'unique_together': {('produto', 'mes_referencia')},
            },
        ),
    ]
