# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GPS', 'GPS'), ('SENSOR_TEMPERATURA', 'Sensor de Temperatura'), ('SENSOR_PRESSAO', 'Sensor de Pressão'), ('TACOGRAFO', 'Tacógrafo'), ('CAMERA', 'Câmera'), ('SENSOR_COMBUSTIVEL', 'Sensor de Combustível'), ('OBD', 'OBD-II'), ('OUTRO', 'Outro')], max_length=30)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('data_instalacao', models.DateField(default=django.utils.timezone.now)),
                ('data_ultima_leitura', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MANUTENCAO', 'Manutenção'), ('DEFEITO', 'Defeito')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='transportador_empresas.empresa')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['veiculo', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('velocidade', models.IntegerField(blank=True, help_text='Velocidade em km/h', null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura em °C', max_digits=5, null=True)),
                ('pressao', models.DecimalField(blank=True, decimal_places=2, help_text='Pressão em PSI', max_digits=5, null=True)),
                ('nivel_combustivel', models.DecimalField(blank=True, decimal_places=2, help_text='Nível em %', max_digits=5, null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('hodometro', models.IntegerField(blank=True, help_text='KM total', null=True)),
                ('dados_json', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='telemetria.dispositivo')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EXCESSO_VELOCIDADE', 'Excesso de Velocidade'), ('TEMPERATURA_ALTA', 'Temperatura Alta'), ('PRESSAO_BAIXA', 'Pressão Baixa'), ('COMBUSTIVEL_BAIXO', 'Combustível Baixo'), ('MANUTENCAO', 'Manutenção Necessária'), ('CERCA_VIOLADA', 'Cerca Eletrônica Violada'), ('DISPOSITIVO_OFFLINE', 'Dispositivo Offline'), ('OUTRO', 'Outro')], max_length=30)),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10)),
                ('mensagem', models.TextField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_reconhecimento', models.DateTimeField(blank=True, null=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('RECONHECIDO', 'Reconhecido'), ('RESOLVIDO', 'Resolvido'), ('IGNORADO', 'Ignorado')], default='ABERTO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='telemetria.dispositivo')),
                ('leitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='telemetria.leitura')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='leitura',
            index=models.Index(fields=['dispositivo', '-data_hora'], name='telemetria__disposi_b08aec_idx'),
        ),
    ]
