# Generated by Django 5.2.7 on 2025-10-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmanutencao',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o checklist pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists_manutencao', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='checklistmanutencao',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o checklist está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists_manutencao', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='itemos',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o item da OS pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_os', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='itemos',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o item da OS está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_os', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual a OS pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual a OS está associada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
    ]
