# Generated by Django 5.2.7 on 2025-10-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0001_initial'),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual a carga pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='carga',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual a carga está associada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='itemcarga',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o item de carga pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_carga', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='itemcarga',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o item de carga está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_carga', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='manifestocarga',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o manifesto de carga pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifestos_carga', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='manifestocarga',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o manifesto de carga está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifestos_carga', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='rastreamentocarga',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o rastreamento de carga pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rastreamentos_carga', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='rastreamentocarga',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o rastreamento de carga está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rastreamentos_carga', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='tipocarga',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o tipo de carga pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_carga', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tipocarga',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o tipo de carga está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_carga', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
    ]
