# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('CENTRAL', 'Central'), ('FILIAL', 'Filial'), ('MOVEL', 'Móvel'), ('TERCEIRIZADO', 'Terceirizado')], default='CENTRAL', max_length=20, verbose_name='Tipo')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Almoxarifado',
                'verbose_name_plural': 'Almoxarifados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InventarioAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_inventario', models.DateField(verbose_name='Data do Inventário')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='almoxarifado.almoxarifado', verbose_name='Almoxarifado')),
            ],
            options={
                'verbose_name': 'Inventário de Almoxarifado',
                'verbose_name_plural': 'Inventários de Almoxarifado',
                'ordering': ['-data_inventario'],
            },
        ),
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('corredor', models.CharField(blank=True, max_length=10, verbose_name='Corredor')),
                ('prateleira', models.CharField(blank=True, max_length=10, verbose_name='Prateleira')),
                ('nivel', models.CharField(blank=True, max_length=10, verbose_name='Nível')),
                ('posicao', models.CharField(blank=True, max_length=10, verbose_name='Posição')),
                ('capacidade_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidade Máxima')),
                ('unidade_capacidade', models.CharField(blank=True, max_length=10, verbose_name='Unidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='almoxarifado.almoxarifado', verbose_name='Almoxarifado')),
            ],
            options={
                'verbose_name': 'Local de Estoque',
                'verbose_name_plural': 'Locais de Estoque',
                'ordering': ['almoxarifado', 'codigo'],
                'unique_together': {('almoxarifado', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=60, verbose_name='Código do Produto')),
                ('descricao_produto', models.CharField(max_length=200, verbose_name='Descrição do Produto')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('quantidade_sistema', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Quantidade no Sistema')),
                ('quantidade_contada', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Quantidade Contada')),
                ('diferenca', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Diferença')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Unitário')),
                ('valor_diferenca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor da Diferença')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('contado_em', models.DateTimeField(blank=True, null=True, verbose_name='Contado em')),
                ('contado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_inventario_contados', to=settings.AUTH_USER_MODEL, verbose_name='Contado por')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='almoxarifado.inventarioalmoxarifado', verbose_name='Inventário')),
                ('local_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_inventario', to='almoxarifado.localestoque', verbose_name='Local de Estoque')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['inventario', 'codigo_produto'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste'), ('DEVOLUCAO', 'Devolução')], max_length=20, verbose_name='Tipo')),
                ('data_movimentacao', models.DateTimeField(verbose_name='Data da Movimentação')),
                ('codigo_produto', models.CharField(max_length=60, verbose_name='Código do Produto')),
                ('descricao_produto', models.CharField(max_length=200, verbose_name='Descrição do Produto')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total')),
                ('documento_referencia', models.CharField(blank=True, max_length=50, verbose_name='Documento de Referência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='almoxarifado.almoxarifado', verbose_name='Almoxarifado')),
                ('almoxarifado_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='almoxarifado.almoxarifado', verbose_name='Almoxarifado Destino')),
                ('local_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='almoxarifado.localestoque', verbose_name='Local de Estoque')),
            ],
            options={
                'verbose_name': 'Movimentação de Almoxarifado',
                'verbose_name_plural': 'Movimentações de Almoxarifado',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_requisicao', models.DateTimeField(verbose_name='Data da Requisição')),
                ('data_necessidade', models.DateField(verbose_name='Data de Necessidade')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('centro_custo', models.CharField(blank=True, max_length=50, verbose_name='Centro de Custo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('EM_SEPARACAO', 'Em Separação'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atendimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='almoxarifado.almoxarifado', verbose_name='Almoxarifado')),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada por')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendida por')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Requisição de Material',
                'verbose_name_plural': 'Requisições de Material',
                'ordering': ['-data_requisicao'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=60, verbose_name='Código do Produto')),
                ('descricao_produto', models.CharField(max_length=200, verbose_name='Descrição do Produto')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade Solicitada')),
                ('quantidade_atendida', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Quantidade Atendida')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='almoxarifado.requisicaomaterial', verbose_name='Requisição')),
            ],
            options={
                'verbose_name': 'Item de Requisição',
                'verbose_name_plural': 'Itens de Requisição',
                'ordering': ['requisicao', 'codigo_produto'],
            },
        ),
    ]
