# Generated by Django 5.2.7 on 2025-10-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almoxarifado',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o almoxarifado pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifados', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='almoxarifado',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o almoxarifado está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifados', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='inventarioalmoxarifado',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o inventário pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_almoxarifado_empresa', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='inventarioalmoxarifado',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o inventário está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_almoxarifado_filial', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o item de inventário pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario_empresa', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o item de inventário está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario_filial', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='localestoque',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o local de estoque pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locais_estoque', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='localestoque',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o local de estoque está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locais_estoque', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='movimentacaoalmoxarifado',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual a movimentação pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_almoxarifado_empresa', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='movimentacaoalmoxarifado',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual a movimentação está associada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_almoxarifado_filial', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
    ]
