# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faturamento', '0001_initial'),
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='viagens.viagem'),
        ),
        migrations.AddField(
            model_name='itemfatura',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturamento.fatura'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='faturamento.fatura'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together={('numero', 'serie')},
        ),
    ]
