# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontuacaoCNH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista_nome', models.CharField(max_length=200)),
                ('motorista_cnh', models.CharField(max_length=20, unique=True)),
                ('pontos_atuais', models.IntegerField(default=0)),
                ('pontos_limite', models.IntegerField(default=20)),
                ('data_ultima_atualizacao', models.DateField(auto_now=True)),
                ('suspenso', models.BooleanField(default=False)),
                ('data_suspensao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pontuação CNH',
                'verbose_name_plural': 'Pontuações CNH',
                'ordering': ['-pontos_atuais'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_auto', models.CharField(max_length=50, unique=True)),
                ('data_infracao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('codigo_infracao', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('LEVE', 'Leve'), ('MEDIA', 'Média'), ('GRAVE', 'Grave'), ('GRAVISSIMA', 'Gravíssima')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pontos_cnh', models.IntegerField(default=0)),
                ('local_infracao', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('motorista_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('motorista_cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_RECURSO', 'Em Recurso'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='transportador_empresas.empresa')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-data_infracao'],
            },
        ),
        migrations.CreateModel(
            name='RecursoMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recurso', models.DateField(default=django.utils.timezone.now)),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.TextField()),
                ('argumentacao', models.TextField()),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('CANCELADO', 'Cancelado')], default='EM_ANALISE', max_length=20)),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='multas.multa')),
            ],
            options={
                'verbose_name': 'Recurso de Multa',
                'verbose_name_plural': 'Recursos de Multas',
                'ordering': ['-data_recurso'],
            },
        ),
    ]
