# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATRASO', 'Atraso'), ('RECUSA', 'Recusa'), ('ENDERECO_INCORRETO', 'Endereço Incorreto'), ('AUSENTE', 'Destinatário Ausente'), ('AVARIA', 'Avaria na Mercadoria'), ('EXTRAVIO', 'Extravio'), ('ROUBO', 'Roubo/Furto'), ('ACIDENTE', 'Acidente'), ('OUTRO', 'Outro')], max_length=30)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto_ocorrencia', models.ImageField(blank=True, null=True, upload_to='ocorrencias/')),
                ('responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='POD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebedor_nome', models.CharField(max_length=200)),
                ('recebedor_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('recebedor_rg', models.CharField(blank=True, max_length=20, null=True)),
                ('data_hora_recebimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('assinatura_digital', models.ImageField(blank=True, null=True, upload_to='pods/assinaturas/')),
                ('foto_comprovante', models.ImageField(blank=True, null=True, upload_to='pods/fotos/')),
                ('latitude_entrega', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude_entrega', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'POD (Proof of Delivery)',
                'verbose_name_plural': 'PODs (Proofs of Delivery)',
                'ordering': ['-data_hora_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tentativa', models.IntegerField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('sucesso', models.BooleanField(default=False)),
                ('motivo_falha', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tentativa de Entrega',
                'verbose_name_plural': 'Tentativas de Entrega',
                'ordering': ['entrega', 'numero_tentativa'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrega', models.CharField(max_length=100, unique=True)),
                ('numero_nota_fiscal', models.CharField(max_length=50)),
                ('destinatario_nome', models.CharField(max_length=200)),
                ('destinatario_cpf_cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('endereco_entrega', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('data_prevista', models.DateTimeField()),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('valor_mercadoria', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumes', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('NAO_ENTREGUE', 'Não Entregue'), ('DEVOLVIDA', 'Devolvida')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='transportador_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-data_prevista'],
            },
        ),
    ]
