# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entregas', '0001_initial'),
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='viagens.viagem'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='entregas.entrega'),
        ),
        migrations.AddField(
            model_name='pod',
            name='entrega',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pod', to='entregas.entrega'),
        ),
        migrations.AddField(
            model_name='tentativa',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='entregas.entrega'),
        ),
        migrations.AlterUniqueTogether(
            name='tentativa',
            unique_together={('entrega', 'numero_tentativa')},
        ),
    ]
