# Generated by Django 5.2.7 on 2025-10-10 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=50, unique=True)),
                ('eixos_aplicaveis', models.CharField(blank=True, help_text='Ex: DIANTEIRO, TRACAO, LIVRE', max_length=100)),
                ('operacao', models.CharField(blank=True, help_text='Tipo de operação recomendada', max_length=100)),
                ('carga_maxima', models.IntegerField(blank=True, help_text='Carga máxima em kg', null=True)),
                ('pressao_recomendada', models.DecimalField(blank=True, decimal_places=1, help_text='Pressão em PSI', max_digits=4, null=True)),
                ('km_recomendado', models.IntegerField(blank=True, help_text='KM recomendado até troca', null=True)),
                ('sulco_minimo', models.DecimalField(decimal_places=2, default=1.6, help_text='Sulco mínimo legal em mm', max_digits=4)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aplicação de Pneu',
                'verbose_name_plural': 'Aplicações de Pneus',
                'ordering': ['medida'],
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('numero_fogo', models.CharField(blank=True, help_text='Número de fogo gravado no pneu', max_length=50, null=True)),
                ('medida', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('NOVO', 'Novo'), ('RECAPADO', 'Recapado'), ('REFORMADO', 'Reformado')], default='NOVO', max_length=20)),
                ('dot', models.CharField(blank=True, help_text='Data de fabricação', max_length=10)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('semana_fabricacao', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ESTOQUE', 'Em Estoque'), ('MONTADO', 'Montado'), ('MANUTENCAO', 'Em Manutenção'), ('SUCATA', 'Sucata'), ('RECAPAGEM', 'Em Recapagem'), ('VENDIDO', 'Vendido')], default='ESTOQUE', max_length=50)),
                ('posicao_atual', models.CharField(blank=True, default='', help_text='Placa-Posição ex: ABC1234-1E', max_length=50)),
                ('km_total', models.IntegerField(default=0, help_text='KM total rodado')),
                ('km_atual', models.IntegerField(default=0, help_text='KM desde última montagem')),
                ('profundidade_sulco', models.DecimalField(blank=True, decimal_places=2, help_text='Profundidade em mm', max_digits=4, null=True)),
                ('numero_recapagens', models.IntegerField(default=0)),
                ('pode_recapar', models.BooleanField(default=True)),
                ('valor_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_montagem', models.DateField(blank=True, null=True)),
                ('data_desmontagem', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pneu',
                'verbose_name_plural': 'Pneus',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoPneu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MONTAGEM', 'Montagem'), ('DESMONTAGEM', 'Desmontagem'), ('RODIZIO', 'Rodízio'), ('RECAPAGEM', 'Envio para Recapagem'), ('RETORNO_RECAPAGEM', 'Retorno de Recapagem'), ('SUCATA', 'Descarte/Sucata'), ('VENDA', 'Venda')], max_length=30)),
                ('origem', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('km_veiculo', models.IntegerField(blank=True, null=True)),
                ('km_pneu', models.IntegerField(blank=True, null=True)),
                ('sulco_medicao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('realizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='pneus.tire')),
            ],
            options={
                'verbose_name': 'Movimentação de Pneu',
                'verbose_name_plural': 'Movimentações de Pneus',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='MedicaoPneu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sulco_externo', models.DecimalField(decimal_places=2, help_text='Sulco externo em mm', max_digits=4)),
                ('sulco_central', models.DecimalField(decimal_places=2, help_text='Sulco central em mm', max_digits=4)),
                ('sulco_interno', models.DecimalField(decimal_places=2, help_text='Sulco interno em mm', max_digits=4)),
                ('pressao', models.DecimalField(blank=True, decimal_places=1, help_text='Pressão em PSI', max_digits=4, null=True)),
                ('km_veiculo', models.IntegerField(blank=True, null=True)),
                ('km_pneu', models.IntegerField(blank=True, null=True)),
                ('desgaste_irregular', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_medicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('medido_por', models.CharField(blank=True, max_length=100, null=True)),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='pneus.tire')),
            ],
            options={
                'verbose_name': 'Medição de Pneu',
                'verbose_name_plural': 'Medições de Pneus',
                'ordering': ['-data_medicao'],
            },
        ),
    ]
