# Generated by Django 5.2.7 on 2025-10-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneus', '0001_initial'),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa proprietária da aplicação de pneu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_pneu', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='application',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial responsável pela aplicação de pneu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_pneu', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='medicaopneu',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa proprietária da medição de pneu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_pneu', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='medicaopneu',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial responsável pela medição de pneu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_pneu', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='movimentacaopneu',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa proprietária da movimentação de pneu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_pneu', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='movimentacaopneu',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial responsável pela movimentação de pneu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_pneu', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='tire',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa proprietária do pneu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pneus', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tire',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial responsável pelo pneu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pneus', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
    ]
