# Generated by Django 5.2.7 on 2025-10-11 04:00
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar_visualizacoes', models.BooleanField(default=False, verbose_name='Registrar Visualizações')),
                ('registrar_exportacoes', models.BooleanField(default=True, verbose_name='Registrar Exportações')),
                ('registrar_alteracoes', models.BooleanField(default=True, verbose_name='Registrar Alterações')),
                ('registrar_exclusoes', models.BooleanField(default=True, verbose_name='Registrar Exclusões')),
                ('dias_retencao_logs', models.PositiveIntegerField(default=365, verbose_name='Dias de Retenção de Logs')),
                ('dias_retencao_logs_acesso', models.PositiveIntegerField(default=90, verbose_name='Dias de Retenção de Logs de Acesso')),
                ('notificar_acessos_suspeitos', models.BooleanField(default=True, verbose_name='Notificar Acessos Suspeitos')),
                ('notificar_alteracoes_criticas', models.BooleanField(default=True, verbose_name='Notificar Alterações Críticas')),
                ('email_notificacao', models.EmailField(blank=True, max_length=254, verbose_name='Email para Notificações')),
                ('modulos_auditados', models.JSONField(default=list, verbose_name='Módulos Auditados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.OneToOneField(blank=True, help_text='Empresa à qual a configuração de auditoria pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_auditoria', to='transportador_empresas.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, help_text='Filial à qual a configuração de auditoria está associada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_auditoria_filial', to='transportador_empresas.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Configuração de Auditoria',
                'verbose_name_plural': 'Configurações de Auditoria',
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FALHO', 'Login Falho'), ('SESSAO_EXPIRADA', 'Sessão Expirada')], max_length=20, verbose_name='Tipo de Acesso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('dispositivo', models.CharField(blank=True, max_length=100, verbose_name='Dispositivo')),
                ('navegador', models.CharField(blank=True, max_length=100, verbose_name='Navegador')),
                ('sistema_operacional', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('motivo_falha', models.TextField(blank=True, verbose_name='Motivo da Falha')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-criado_em'],
                'indexes': [
                    models.Index(fields=['usuario', 'criado_em'], name='logacesso_usuario_criado_idx'),
                    models.Index(fields=['tipo_acesso', 'criado_em'], name='logacesso_tipo_criado_idx'),
                    models.Index(fields=['ip_address', 'criado_em'], name='logacesso_ip_criado_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SessaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Chave da Sessão')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('dispositivo', models.CharField(blank=True, max_length=100, verbose_name='Dispositivo')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em')),
                ('ultima_atividade', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('encerrada_em', models.DateTimeField(blank=True, null=True, verbose_name='Encerrada em')),
                ('motivo_encerramento', models.CharField(blank=True, choices=[('LOGOUT', 'Logout'), ('TIMEOUT', 'Timeout'), ('ADMIN', 'Encerrada pelo Admin'), ('NOVA_SESSAO', 'Nova Sessão Iniciada')], max_length=50, verbose_name='Motivo do Encerramento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Usuário',
                'verbose_name_plural': 'Sessões de Usuário',
                'ordering': ['-iniciada_em'],
                'indexes': [
                    models.Index(fields=['usuario', 'ativa'], name='sessaousuario_usuario_ativa_idx'),
                    models.Index(fields=['session_key'], name='sessaousuario_session_idx'),
                    models.Index(fields=['ultima_atividade'], name='sessaousuario_ultima_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR', 'Criar'), ('ATUALIZAR', 'Atualizar'), ('DELETAR', 'Deletar'), ('VISUALIZAR', 'Visualizar'), ('EXPORTAR', 'Exportar'), ('IMPORTAR', 'Importar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ERRO', 'Erro')], max_length=20, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('severidade', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico')], default='INFO', max_length=20, verbose_name='Severidade')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metodo_http', models.CharField(blank=True, max_length=10, verbose_name='Método HTTP')),
                ('url', models.TextField(blank=True, verbose_name='URL')),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('modulo', models.CharField(blank=True, max_length=100, verbose_name='Módulo')),
                ('funcao', models.CharField(blank=True, max_length=100, verbose_name='Função')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('stack_trace', models.TextField(blank=True, verbose_name='Stack Trace')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa à qual o log de auditoria pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria_empresa', to='transportador_empresas.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, help_text='Filial à qual o log de auditoria está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria_filial', to='transportador_empresas.filial', verbose_name='Filial')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
                'indexes': [
                    models.Index(fields=['usuario', 'criado_em'], name='logauditoria_usuario_criado_idx'),
                    models.Index(fields=['empresa', 'criado_em'], name='logauditoria_empresa_criado_idx'),
                    models.Index(fields=['acao', 'criado_em'], name='logauditoria_acao_criado_idx'),
                    models.Index(fields=['severidade', 'criado_em'], name='logauditoria_severidade_idx'),
                    models.Index(fields=['content_type', 'object_id'], name='logauditoria_content_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='LogAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Objeto')),
                ('object_repr', models.CharField(max_length=200, verbose_name='Representação do Objeto')),
                ('tipo_alteracao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão')], max_length=20, verbose_name='Tipo de Alteração')),
                ('campo', models.CharField(max_length=100, verbose_name='Campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='Valor Novo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa à qual o log de alteração pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_alteracao_empresa', to='transportador_empresas.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, help_text='Filial à qual o log de alteração está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_alteracao_filial', to='transportador_empresas.filial', verbose_name='Filial')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_alteracao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Alteração',
                'verbose_name_plural': 'Logs de Alteração',
                'ordering': ['-criado_em'],
                'indexes': [
                    models.Index(fields=['content_type', 'object_id', 'criado_em'], name='logalteracao_content_idx'),
                    models.Index(fields=['usuario', 'criado_em'], name='logalteracao_usuario_idx'),
                    models.Index(fields=['tipo_alteracao', 'criado_em'], name='logalteracao_tipo_idx'),
                ],
            },
        ),
    ]
