# Generated by Django 5.2.7 on 2025-10-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTransportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome_razao_social', models.CharField(max_length=200, verbose_name='Nome/Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuário')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('aprovado_por', models.CharField(blank=True, max_length=200, verbose_name='Aprovado por')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_transportadores', to='transportador_empresas.empresa', verbose_name='Empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuario_transportador_set', related_query_name='usuario_transportador', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_transportador_permissions', related_query_name='usuario_transportador_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário Transportador',
                'verbose_name_plural': 'Usuários Transportadores',
                'db_table': 'transportador_usuario',
            },
        ),
    ]
