# Generated by Django 5.2.7 on 2025-10-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportador', '0002_alter_usuariotransportador_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotransportador',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
    ]
