# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('SALARIO', 'Salário'), ('IMPOSTO', 'Imposto'), ('ALUGUEL', 'Aluguel'), ('COMBUSTIVEL', 'Combustível'), ('MANUTENCAO', 'Manutenção'), ('SEGURO', 'Seguro'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='transportador_empresas.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDA', 'Recebida'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='transportador_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('TED', 'TED'), ('BOLETO', 'Boleto'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='pagamentos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pagamentos.contapagar')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='pagamentos.contareceber')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
