# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transportador_empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In-App')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('configuracao_json', models.JSONField(blank=True, help_text='Configurações como API keys, endpoints, etc', null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_notificacao', to='transportador_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Canal de Notificação',
                'verbose_name_plural': 'Canais de Notificação',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('empresa', 'tipo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_habilitado', models.BooleanField(default=True)),
                ('sms_habilitado', models.BooleanField(default=False)),
                ('push_habilitado', models.BooleanField(default=True)),
                ('whatsapp_habilitado', models.BooleanField(default=False)),
                ('categorias_json', models.JSONField(blank=True, help_text='Categorias que o usuário deseja receber', null=True)),
                ('silencio_inicio', models.TimeField(blank=True, null=True)),
                ('silencio_fim', models.TimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacao', to='transportador_empresas.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
            },
        ),
        migrations.CreateModel(
            name='TemplateNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=50)),
                ('template_email_assunto', models.CharField(blank=True, max_length=200, null=True)),
                ('template_email_corpo', models.TextField(blank=True, null=True)),
                ('template_sms', models.CharField(blank=True, max_length=160, null=True)),
                ('template_push_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('template_push_corpo', models.CharField(blank=True, max_length=200, null=True)),
                ('variaveis_json', models.JSONField(blank=True, help_text='Lista de variáveis disponíveis no template', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_notificacao', to='transportador_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('destinatario_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIANDO', 'Enviando'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida'), ('FALHA', 'Falha')], default='PENDENTE', max_length=20)),
                ('categoria', models.CharField(blank=True, help_text='Ex: manutencao, viagem, financeiro', max_length=50, null=True)),
                ('referencia_tipo', models.CharField(blank=True, help_text='Tipo do objeto relacionado', max_length=50, null=True)),
                ('referencia_id', models.IntegerField(blank=True, help_text='ID do objeto relacionado', null=True)),
                ('agendada_para', models.DateTimeField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.IntegerField(default=0)),
                ('max_tentativas', models.IntegerField(default=3)),
                ('erro_mensagem', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='notificacoes.canalnotificacao')),
                ('destinatario_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='transportador_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['destinatario_usuario', 'status'], name='notificacoe_destina_54b5ba_idx'), models.Index(fields=['status', 'agendada_para'], name='notificacoe_status_9d31a9_idx')],
            },
        ),
    ]
