# Generated by Django 5.2.7 on 2025-10-11 04:05
from decimal import Decimal

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('serie', models.CharField(max_length=10, verbose_name='Série')),
                ('modelo', models.CharField(choices=[('55', 'NF-e (Modelo 55)'), ('65', 'NFC-e (Modelo 65)'), ('57', 'CT-e (Modelo 57)'), ('NFSE', 'NFS-e')], default='55', max_length=10, verbose_name='Modelo')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('SERVICO', 'Serviço'), ('DEVOLUCAO', 'Devolução')], default='SAIDA', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EMITIDA', 'Emitida'), ('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('DENEGADA', 'Denegada'), ('REJEITADA', 'Rejeitada')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('data_emissao', models.DateTimeField(verbose_name='Data de Emissão')),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Autorização')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('emitente_cnpj', models.CharField(max_length=18, verbose_name='CNPJ Emitente')),
                ('emitente_nome', models.CharField(max_length=200, verbose_name='Nome Emitente')),
                ('emitente_ie', models.CharField(blank=True, max_length=20, verbose_name='IE Emitente')),
                ('destinatario_cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ Destinatário')),
                ('destinatario_nome', models.CharField(max_length=200, verbose_name='Nome Destinatário')),
                ('destinatario_ie', models.CharField(blank=True, max_length=20, verbose_name='IE Destinatário')),
                ('destinatario_endereco', models.TextField(blank=True, verbose_name='Endereço Destinatário')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[MinValueValidator(Decimal('0.00'))], verbose_name='Valor Produtos')),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[MinValueValidator(Decimal('0.00'))], verbose_name='Valor Serviços')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[MinValueValidator(Decimal('0.00'))], verbose_name='Valor Desconto')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[MinValueValidator(Decimal('0.00'))], verbose_name='Valor Frete')),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[MinValueValidator(Decimal('0.00'))], verbose_name='Valor Seguro')),
                ('valor_outras_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[MinValueValidator(Decimal('0.00'))], verbose_name='Outras Despesas')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('base_calculo_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Base Cálculo ICMS')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor ICMS')),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor IPI')),
                ('valor_pis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor PIS')),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor COFINS')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, unique=True, verbose_name='Chave de Acesso')),
                ('protocolo_autorizacao', models.CharField(blank=True, max_length=50, verbose_name='Protocolo de Autorização')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do Cancelamento')),
                ('xml_enviado', models.TextField(blank=True, verbose_name='XML Enviado')),
                ('xml_retorno', models.TextField(blank=True, verbose_name='XML Retorno')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('informacoes_complementares', models.TextField(blank=True, verbose_name='Informações Complementares')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='transportador_empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao', '-numero'],
                'indexes': [
                    models.Index(fields=['empresa', 'status'], name='notafiscal_empresa_status_idx'),
                    models.Index(fields=['chave_acesso'], name='notafiscal_chave_idx'),
                    models.Index(fields=['destinatario_cpf_cnpj'], name='notafiscal_destinatario_idx'),
                ],
                'unique_together': {('empresa', 'numero', 'serie', 'modelo')},
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(verbose_name='Número do Item')),
                ('codigo_produto', models.CharField(max_length=60, verbose_name='Código do Produto')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('ncm', models.CharField(blank=True, max_length=8, verbose_name='NCM')),
                ('cfop', models.CharField(max_length=4, verbose_name='CFOP')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15, validators=[MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=15, validators=[MinValueValidator(Decimal('0.0001'))], verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Desconto')),
                ('aliquota_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Alíquota ICMS (%)')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor ICMS')),
                ('aliquota_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Alíquota IPI (%)')),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor IPI')),
                ('informacoes_adicionais', models.TextField(blank=True, verbose_name='Informações Adicionais')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='notas_fiscais.notafiscal', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Item de Nota Fiscal',
                'verbose_name_plural': 'Itens de Nota Fiscal',
                'ordering': ['nota_fiscal', 'numero_item'],
                'unique_together': {('nota_fiscal', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='ImpostoNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_imposto', models.CharField(max_length=20, verbose_name='Tipo de Imposto')),
                ('base_calculo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Base de Cálculo')),
                ('aliquota', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Alíquota (%)')),
                ('valor_imposto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor do Imposto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impostos', to='notas_fiscais.notafiscal', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Imposto de Nota Fiscal',
                'verbose_name_plural': 'Impostos de Nota Fiscal',
                'ordering': ['nota_fiscal', 'tipo_imposto'],
            },
        ),
        migrations.CreateModel(
            name='AnexoNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='notas_fiscais/anexos/%Y/%m/', verbose_name='Arquivo')),
                ('tipo_arquivo', models.CharField(max_length=50, verbose_name='Tipo de Arquivo')),
                ('tamanho_arquivo', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='notas_fiscais.notafiscal', verbose_name='Nota Fiscal')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_nf_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Anexo de Nota Fiscal',
                'verbose_name_plural': 'Anexos de Nota Fiscal',
                'ordering': ['-criado_em'],
            },
        ),
    ]
