# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FIXO', 'Custo Fixo'), ('VARIAVEL', 'Custo Variável'), ('OPERACIONAL', 'Operacional'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Custo',
                'verbose_name_plural': 'Categorias de Custos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_custo', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('km_veiculo', models.IntegerField(blank=True, help_text='KM do veículo no momento do custo', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos', to='custos.categoriacusto')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Custo',
                'verbose_name_plural': 'Custos',
                'ordering': ['-data_custo'],
            },
        ),
        migrations.CreateModel(
            name='CustoPorKm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('km_inicial', models.IntegerField()),
                ('km_final', models.IntegerField()),
                ('km_rodado', models.IntegerField()),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_por_km', models.DecimalField(decimal_places=4, max_digits=10)),
                ('custo_combustivel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_manutencao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_pneus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_outros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_km', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Custo por KM',
                'verbose_name_plural': 'Custos por KM',
                'ordering': ['-mes_referencia'],
                'unique_together': {('veiculo', 'mes_referencia')},
            },
        ),
    ]
