# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('transportador_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoristaInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('categoria_cnh', models.CharField(default='D', max_length=5)),
                ('validade_cnh', models.DateField()),
                ('numero_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'CLT'), ('AGREGADO', 'Agregado'), ('TERCEIRO', 'Terceiro'), ('TEMPORARIO', 'Temporário')], default='CLT', max_length=20)),
                ('data_admissao', models.DateField(default=django.utils.timezone.now)),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('FERIAS', 'Férias'), ('AFASTADO', 'Afastado'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=20)),
                ('motorista_externo_id', models.CharField(blank=True, help_text='ID do motorista no sistema externo', max_length=100, null=True)),
                ('conectado_app', models.BooleanField(default=False, help_text='Motorista conectado ao app externo')),
                ('ultimo_acesso_app', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motoristas_internos', to='transportador_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Motorista Interno',
                'verbose_name_plural': 'Motoristas Internos',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='MensagemMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENVIADA', 'Enviada ao Motorista'), ('RECEBIDA', 'Recebida do Motorista')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=200, null=True)),
                ('mensagem', models.TextField()),
                ('anexo_url', models.URLField(blank=True, null=True)),
                ('anexo_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensagem_resposta_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='motorista_interno.mensagemmotorista')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='motorista_interno.motoristainterno')),
            ],
            options={
                'verbose_name': 'Mensagem Motorista',
                'verbose_name_plural': 'Mensagens Motoristas',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='AlertaMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CNH_VENCENDO', 'CNH Vencendo'), ('CNH_VENCIDA', 'CNH Vencida'), ('JORNADA_EXCEDIDA', 'Jornada Excedida'), ('FALTA_REGISTRO', 'Falta Registro de Jornada'), ('MANUTENCAO_PENDENTE', 'Manutenção Pendente'), ('OUTRO', 'Outro')], max_length=30)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido'), ('IGNORADO', 'Ignorado')], default='ABERTO', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_alerta', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('resolvido_por', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes_resolucao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='motorista_interno.motoristainterno')),
            ],
            options={
                'verbose_name': 'Alerta Motorista',
                'verbose_name_plural': 'Alertas Motoristas',
                'ordering': ['-data_alerta', '-prioridade'],
            },
        ),
        migrations.CreateModel(
            name='RegistroJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(choices=[('INICIO', 'Início de Jornada'), ('PAUSA', 'Pausa'), ('RETORNO', 'Retorno da Pausa'), ('FIM', 'Fim de Jornada')], max_length=20)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('origem', models.CharField(choices=[('APP', 'App Externo'), ('MANUAL', 'Manual'), ('SISTEMA', 'Sistema')], default='APP', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('localizacao_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('km_veiculo', models.IntegerField(blank=True, help_text='Quilometragem do veículo no momento do registro', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('app_versao', models.CharField(blank=True, max_length=20, null=True)),
                ('dispositivo_id', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_jornada', to='motorista_interno.motoristainterno')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_jornada', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Registro de Jornada',
                'verbose_name_plural': 'Registros de Jornada',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='VinculoMotoristaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_veiculo', to='motorista_interno.motoristainterno')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_motorista', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Vínculo Motorista-Veículo',
                'verbose_name_plural': 'Vínculos Motorista-Veículo',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
