# Generated by Django 5.2.7 on 2025-10-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista_interno', '0001_initial'),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertamotorista',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o alerta pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_motorista_empresa', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='alertamotorista',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o alerta está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_motorista_filial', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='mensagemmotorista',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual a mensagem pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_motorista_empresa', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='mensagemmotorista',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual a mensagem está associada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_motorista_filial', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='motoristainterno',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o motorista interno está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motoristas_internos_filial', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='registrojornada',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o registro de jornada pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_jornada_empresa', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='registrojornada',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o registro de jornada está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_jornada_filial', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='vinculomotoristaveiculo',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o vínculo pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_motorista_veiculo_empresa', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='vinculomotoristaveiculo',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial à qual o vínculo está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_motorista_veiculo_filial', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='motoristainterno',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o motorista interno está vinculado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motoristas_internos_empresa', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
    ]
