# Generated by Django 5.2.7 on 2025-10-14 15:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0005_historicokm_empresa_historicokm_filial_and_more'),
        ('motorista_interno', '0001_initial'),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoristaExterno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cnh', models.CharField(max_length=20, unique=True, verbose_name='CNH')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa à qual o motorista externo está vinculado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motoristas_externos_empresa', to='transportador_empresas.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, help_text='Filial à qual o motorista externo está associado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motoristas_externos_filial', to='transportador_empresas.filial', verbose_name='Filial')),
                ('usuario', models.OneToOneField(blank=True, help_text='Vínculo com o usuário do Django para autenticação', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista_externo_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Motorista Externo',
                'verbose_name_plural': 'Motoristas Externos',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='AlocacaoMotorista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20, verbose_name='Status da Alocação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa à qual a alocação pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_motorista_empresa', to='transportador_empresas.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, help_text='Filial à qual a alocação está associada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_motorista_filial', to='transportador_empresas.filial', verbose_name='Filial')),
                ('motorista_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_veiculo', to='motorista_interno.motoristainterno', verbose_name='Motorista Interno')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_motorista', to='frota.vehicle', verbose_name='Veículo Alocado')),
                ('motorista_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_veiculo', to='motorista_externo.motoristaexterno', verbose_name='Motorista Externo')),
            ],
            options={
                'verbose_name': 'Alocação de Motorista',
                'verbose_name_plural': 'Alocações de Motoristas',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
