# Generated by Django 5.2.7 on 2025-10-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista_externo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoristaexterno',
            name='aprovado',
            field=models.BooleanField(default=False, help_text='Indica se o motorista externo foi aprovado por um administrador', verbose_name='Aprovado'),
        ),
    ]
