# Generated by Django 5.2.7 on 2025-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista_externo', '0002_motoristaexterno_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoristaexterno',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
