# Generated by Django 5.2.7 on 2025-10-10 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('ano_modelo', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('CAMINHAO', 'Caminhão'), ('CARRETA', 'Carreta'), ('BITREM', 'Bitrem'), ('RODOTREM', 'Rodotrem'), ('VUC', 'VUC'), ('OUTRO', 'Outro')], default='CAMINHAO', max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo'), ('VENDIDO', 'Vendido')], default='ATIVO', max_length=20)),
                ('km', models.IntegerField(default=0, help_text='Quilometragem atual')),
                ('km_ultima_manutencao', models.IntegerField(default=0)),
                ('km_proxima_manutencao', models.IntegerField(blank=True, null=True)),
                ('motorista', models.CharField(blank=True, max_length=100, null=True)),
                ('chassi', models.CharField(blank=True, max_length=50, null=True)),
                ('renavam', models.CharField(blank=True, max_length=20, null=True)),
                ('capacidade_carga', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidade em toneladas', max_digits=10, null=True)),
                ('numero_eixos', models.IntegerField(default=3)),
                ('total_posicoes_pneus', models.IntegerField(default=6, help_text='Total de posições para pneus')),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_venda', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoKm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_anterior', models.IntegerField()),
                ('km_atual', models.IntegerField()),
                ('km_rodado', models.IntegerField()),
                ('data_leitura', models.DateTimeField(default=django.utils.timezone.now)),
                ('origem', models.CharField(default='MANUAL', help_text='MANUAL, APP, TELEMETRIA', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_km', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Histórico de KM',
                'verbose_name_plural': 'Históricos de KM',
                'ordering': ['-data_leitura'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(help_text='Ex: 1E, 1D, 2E, 2D', max_length=50)),
                ('eixo', models.IntegerField(help_text='Número do eixo')),
                ('tipo_eixo', models.CharField(choices=[('DIANTEIRO', 'Dianteiro'), ('TRACAO', 'Tração'), ('LIVRE', 'Livre')], default='LIVRE', max_length=20)),
                ('lado', models.CharField(choices=[('E', 'Esquerdo'), ('D', 'Direito')], max_length=1)),
                ('medida', models.CharField(help_text='Medida do pneu recomendada', max_length=50)),
                ('pneu_atual_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_pneu', to='frota.vehicle')),
            ],
            options={
                'verbose_name': 'Posição de Pneu',
                'verbose_name_plural': 'Posições de Pneus',
                'ordering': ['veiculo', 'ordem', 'eixo', 'lado'],
                'unique_together': {('veiculo', 'posicao')},
            },
        ),
    ]
