# Generated by Django 5.2.7 on 2025-10-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa proprietária do veículo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial responsável pelo veículo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
    ]
