# Generated by Django 5.2.7 on 2025-10-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_vehicle_empresa_vehicle_filial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['veiculo', 'ordem'], 'verbose_name': 'Posição de Pneu', 'verbose_name_plural': 'Posições de Pneus'},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('veiculo', 'ordem')},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='numero_eixos',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='total_posicoes_pneus',
        ),
        migrations.RemoveField(
            model_name='position',
            name='eixo',
        ),
        migrations.RemoveField(
            model_name='position',
            name='lado',
        ),
        migrations.RemoveField(
            model_name='position',
            name='medida',
        ),
        migrations.RemoveField(
            model_name='position',
            name='pneu_atual_codigo',
        ),
        migrations.RemoveField(
            model_name='position',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='position',
            name='tipo_eixo',
        ),
    ]
