# Generated by Django 5.2.7 on 2025-10-13 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_alter_mapaposicaopneu_position_id'),
        ('frota', '0003_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='position',
            name='mapa_posicao',
            field=models.ForeignKey(blank=True, help_text='Mapeamento da posição do pneu no veículo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posicoes_veiculos_mapa', to='configuracoes.mapaposicaopneu', verbose_name='Mapa de Posição'),
        ),
        migrations.AddField(
            model_name='position',
            name='medida_recomendada',
            field=models.ForeignKey(blank=True, help_text='Medida de pneu recomendada para esta posição', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posicoes_veiculos_medida', to='configuracoes.medidaporposicao', verbose_name='Medida Recomendada'),
        ),
        migrations.AddField(
            model_name='position',
            name='pneu_atual_codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='configuracao_operacional',
            field=models.ForeignKey(blank=True, help_text='Configuração de eixos e operação do veículo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos_por_operacao', to='configuracoes.operacaoconfiguracao', verbose_name='Configuração Operacional'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='modelo_veiculo',
            field=models.ForeignKey(blank=True, help_text='Modelo de veículo do catálogo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos_por_modelo', to='configuracoes.catalogomodeloveiculo', verbose_name='Modelo de Veículo'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('veiculo', 'mapa_posicao')},
        ),
    ]
