# Generated by Django 5.2.7 on 2025-10-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0004_alter_position_unique_together_position_mapa_posicao_and_more'),
        ('transportador_empresas', '0002_alter_empresa_options_empresa_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicokm',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa proprietária do histórico de KM', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos_km', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicokm',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial responsável pelo histórico de KM', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos_km', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='position',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa proprietária da posição de pneu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posicoes', to='transportador_empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='position',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial responsável pela posição de pneu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posicoes', to='transportador_empresas.filial', verbose_name='Filial'),
        ),
    ]
