# Generated by Django 5.2.7 on 2025-10-13 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CAMINHAO_TRATOR', 'Caminhão/Trator'), ('CAMINHAO_RIGIDO', 'Caminhão Rígido'), ('ONIBUS_CHASSI', 'Ônibus (Chassi)'), ('VANS', 'Vans')], max_length=50, verbose_name='Categoria')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('familia_modelo', models.CharField(max_length=100, verbose_name='Família/Modelo')),
                ('variante', models.CharField(max_length=200, verbose_name='Variante')),
                ('ano_inicio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Ano Início')),
                ('ano_fim', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Ano Fim')),
                ('configuracoes', models.TextField(help_text='Configurações de eixos separadas por |', verbose_name='Configurações')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Catálogo de Modelo de Veículo',
                'verbose_name_plural': 'Catálogo de Modelos de Veículos',
                'ordering': ['marca', 'familia_modelo', 'ano_inicio'],
                'indexes': [models.Index(fields=['marca', 'familia_modelo'], name='configuraco_marca_f7249e_idx'), models.Index(fields=['categoria'], name='configuraco_categor_561062_idx')],
            },
        ),
        migrations.CreateModel(
            name='CatalogoPneuXBRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.CharField(db_index=True, max_length=50, verbose_name='Linha')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('medida', models.CharField(db_index=True, max_length=50, verbose_name='Medida')),
                ('ply_rating', models.CharField(max_length=20, verbose_name='Ply Rating')),
                ('aro_recomendado', models.CharField(max_length=20, verbose_name='Aro Recomendado')),
                ('indice_carga', models.CharField(max_length=50, verbose_name='Índice de Carga')),
                ('indice_velocidade', models.CharField(max_length=10, verbose_name='Índice de Velocidade')),
                ('largura_banda_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Largura Banda (mm)')),
                ('largura_secao_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Largura Seção (mm)')),
                ('profundidade_sulco_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Profundidade Sulco (mm)')),
                ('diametro_externo_mm', models.IntegerField(blank=True, null=True, verbose_name='Diâmetro Externo (mm)')),
                ('pressao_max_psi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pressão Máx (PSI)')),
                ('fonte', models.URLField(blank=True, max_length=500, verbose_name='Fonte')),
                ('li_single_num', models.IntegerField(blank=True, null=True, verbose_name='LI Single')),
                ('li_dual_num', models.IntegerField(blank=True, null=True, verbose_name='LI Dual')),
                ('linha_canonica', models.CharField(max_length=100, verbose_name='Linha Canônica')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Catálogo de Pneu XBRI',
                'verbose_name_plural': 'Catálogo de Pneus XBRI',
                'ordering': ['linha', 'modelo', 'medida'],
                'indexes': [models.Index(fields=['linha', 'modelo'], name='configuraco_linha_7c5cbc_idx'), models.Index(fields=['medida'], name='configuraco_medida_f49448_idx'), models.Index(fields=['linha_canonica'], name='configuraco_linha_c_6a81f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='MapaPosicaoPneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(db_index=True, max_length=50, verbose_name='Config ID')),
                ('componente', models.CharField(choices=[('T', 'Trator'), ('R', 'Rígido'), ('SR1', 'Semi-reboque 1'), ('SR2', 'Semi-reboque 2'), ('DOL', 'Dolly')], max_length=10, verbose_name='Componente')),
                ('eixo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Eixo')),
                ('lado', models.CharField(choices=[('L', 'Esquerdo'), ('R', 'Direito')], max_length=1, verbose_name='Lado')),
                ('rodado', models.CharField(choices=[('S', 'Singelo'), ('IN', 'Interno (Duplo)'), ('EX', 'Externo (Duplo)')], max_length=2, verbose_name='Rodado')),
                ('posicao_tipo', models.CharField(choices=[('direcao', 'Direção'), ('tracao', 'Tração'), ('auxiliar', 'Auxiliar'), ('sr', 'Semi-reboque'), ('dolly', 'Dolly')], max_length=20, verbose_name='Tipo de Posição')),
                ('position_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Position ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Mapa de Posição de Pneu',
                'verbose_name_plural': 'Mapa de Posições de Pneus',
                'ordering': ['config_id', 'componente', 'eixo', 'lado', 'rodado'],
                'indexes': [models.Index(fields=['config_id', 'posicao_tipo'], name='configuraco_config__18f99d_idx'), models.Index(fields=['position_id'], name='configuraco_positio_a6e9ae_idx')],
                'unique_together': {('config_id', 'componente', 'eixo', 'lado', 'rodado')},
            },
        ),
        migrations.CreateModel(
            name='MedidaPorPosicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(db_index=True, max_length=50, verbose_name='Config ID')),
                ('posicao_tipo', models.CharField(max_length=20, verbose_name='Tipo de Posição')),
                ('medidas_tipicas', models.TextField(help_text='Medidas separadas por ;', verbose_name='Medidas Típicas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Medida por Posição',
                'verbose_name_plural': 'Medidas por Posição',
                'ordering': ['config_id', 'posicao_tipo'],
                'indexes': [models.Index(fields=['config_id', 'posicao_tipo'], name='configuraco_config__a601f3_idx')],
                'unique_together': {('config_id', 'posicao_tipo')},
            },
        ),
        migrations.CreateModel(
            name='OperacaoConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código da Operação')),
                ('config_ids_recomendados', models.TextField(help_text='IDs separados por |', verbose_name='Configs Recomendadas')),
                ('implementos_recomendados', models.TextField(verbose_name='Implementos Recomendados')),
                ('eixos_tipicos', models.CharField(max_length=50, verbose_name='Eixos Típicos')),
                ('pbtc_faixa_aprox_t', models.CharField(max_length=50, verbose_name='PBTC Faixa Aprox (t)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Operação e Configuração',
                'verbose_name_plural': 'Operações e Configurações',
                'ordering': ['op_code'],
                'indexes': [models.Index(fields=['op_code'], name='configuraco_op_code_85e8ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='PressaoRecomendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CAMINHAO_TRATOR', 'Caminhão/Trator'), ('CAMINHAO_RIGIDO', 'Caminhão Rígido'), ('IMPLEMENTO_SR', 'Implemento (SR)'), ('COMBINADO', 'Combinado'), ('ONIBUS', 'Ônibus'), ('VANS', 'Vans')], max_length=50, verbose_name='Categoria')),
                ('config_id', models.CharField(blank=True, max_length=50, verbose_name='Config ID')),
                ('posicao_tipo', models.CharField(max_length=20, verbose_name='Tipo de Posição')),
                ('medida_exemplo', models.CharField(max_length=50, verbose_name='Medida Exemplo')),
                ('faixa_psi_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='PSI Mínimo')),
                ('faixa_psi_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='PSI Máximo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pressão Recomendada',
                'verbose_name_plural': 'Pressões Recomendadas',
                'ordering': ['categoria', 'config_id', 'posicao_tipo'],
                'indexes': [models.Index(fields=['categoria', 'config_id'], name='configuraco_categor_c09c51_idx'), models.Index(fields=['posicao_tipo'], name='configuraco_posicao_8d15d8_idx')],
            },
        ),
    ]
