# Generated by Django 5.2.7 on 2025-10-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_catalogomodeloveiculo_catalogopneuxbri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapaposicaopneu',
            name='position_id',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Position ID'),
        ),
    ]
