# Generated by Django 5.2.7 on 2025-10-10 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('PRESTACAO_SERVICO', 'Prestação de Serviço'), ('FORNECIMENTO', 'Fornecimento'), ('LOCACAO', 'Locação'), ('PARCERIA', 'Parceria'), ('OUTRO', 'Outro')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('renovacao_automatica', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('RENOVADO', 'Renovado')], default='RASCUNHO', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='clientes.cliente')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aditivo', models.CharField(max_length=50)),
                ('data_aditivo', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('alteracao_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alteracao_prazo_dias', models.IntegerField(default=0)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='contratos/aditivos/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Aditivo Contratual',
                'verbose_name_plural': 'Aditivos Contratuais',
                'ordering': ['-data_aditivo'],
            },
        ),
    ]
